# Here we specify what causes the pipeline to run; in this case changes to any branch
trigger:
- '*'

# Here we specify what type of machine (agent) to run on
pool:
  vmImage: 'ubuntu-latest'

# And here we specify a list of "jobs"
jobs:
  - job: buildAndTest
    displayName: "Build and Test Job"
    steps:
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.x'
      - script: dotnet build
        displayName: 'Build C# code'
      - script: dotnet test
        displayName: 'Run C# tests'
      - task: UseNode@1
        inputs:
          version: '20.x'
      - script: |
          cd DotnetTemplate.Web
          npm install
        displayName: 'Install TypeScript dependencies'
      - script: |
          cd DotnetTemplate.Web
          npm run build
        displayName: 'Build TypeScript code'
      - script: |
          cd DotnetTemplate.Web
          npm run lint
        displayName: 'Run TypeScript lint'
      - script: |
          cd DotnetTemplate.Web
          npm test
        displayName: 'Run TypeScript tests'