name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build C# code
        run: dotnet build

      - name: Run C# tests
        run: dotnet test

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install TypeScript dependencies
        run: npm install
        working-directory: DotnetTemplate.Web

      - name: Build TypeScript code
        run: npm run build
        working-directory: DotnetTemplate.Web

      - name: Run TypeScript lint
        run: npm run lint
        working-directory: DotnetTemplate.Web

      - name: Run TypeScript tests
        run: npm t
        working-directory: DotnetTemplate.Web